default:
  endpoint: http://graphdb.dumontierlab.com/repositories/trek
  # endpoint: http://localhost:7200/repositories/demo
logging:
  level:
    org:
      semanticscience: INFO
      springframework: ERROR
server:
  port: 8080
# Avoid getting null fields in JSON response
spring.jackson.default-property-inclusion: non_null