default:
  # endpoint: http://graphdb.dumontierlab.com/repositories/ncats-red-kg
  # endpoint: http://localhost:7200/repositories/test
  endpoint: http://graphdb.dumontierlab.com/repositories/trek
logging:
  level:
    org:
      semanticscience: INFO
      springframework: ERROR
server:
  port: 8080
